// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: createpdffile.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PDFCreatorClient is the client API for PDFCreator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PDFCreatorClient interface {
	CreatePDF(ctx context.Context, in *CreatePDFRequest, opts ...grpc.CallOption) (*CreatePDFResponse, error)
}

type pDFCreatorClient struct {
	cc grpc.ClientConnInterface
}

func NewPDFCreatorClient(cc grpc.ClientConnInterface) PDFCreatorClient {
	return &pDFCreatorClient{cc}
}

func (c *pDFCreatorClient) CreatePDF(ctx context.Context, in *CreatePDFRequest, opts ...grpc.CallOption) (*CreatePDFResponse, error) {
	out := new(CreatePDFResponse)
	err := c.cc.Invoke(ctx, "/createpdffile.PDFCreator/CreatePDF", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PDFCreatorServer is the server API for PDFCreator service.
// All implementations must embed UnimplementedPDFCreatorServer
// for forward compatibility
type PDFCreatorServer interface {
	CreatePDF(context.Context, *CreatePDFRequest) (*CreatePDFResponse, error)
	mustEmbedUnimplementedPDFCreatorServer()
}

// UnimplementedPDFCreatorServer must be embedded to have forward compatible implementations.
type UnimplementedPDFCreatorServer struct {
}

func (UnimplementedPDFCreatorServer) CreatePDF(context.Context, *CreatePDFRequest) (*CreatePDFResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePDF not implemented")
}
func (UnimplementedPDFCreatorServer) mustEmbedUnimplementedPDFCreatorServer() {}

// UnsafePDFCreatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PDFCreatorServer will
// result in compilation errors.
type UnsafePDFCreatorServer interface {
	mustEmbedUnimplementedPDFCreatorServer()
}

func RegisterPDFCreatorServer(s grpc.ServiceRegistrar, srv PDFCreatorServer) {
	s.RegisterService(&PDFCreator_ServiceDesc, srv)
}

func _PDFCreator_CreatePDF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePDFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PDFCreatorServer).CreatePDF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/createpdffile.PDFCreator/CreatePDF",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PDFCreatorServer).CreatePDF(ctx, req.(*CreatePDFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PDFCreator_ServiceDesc is the grpc.ServiceDesc for PDFCreator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PDFCreator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "createpdffile.PDFCreator",
	HandlerType: (*PDFCreatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePDF",
			Handler:    _PDFCreator_CreatePDF_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "createpdffile.proto",
}
